apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: security-ingress-cams
  namespace: security
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cams.hospitalsm.org
      secretName: security-tls-secret
  rules:
    - host: cams.hospitalsm.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hsm-security-cams-frigate-ui
                port:
                  number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: security-ingress-vault
  namespace: security
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vault.hospitalsm.org
      secretName: security-tls-secret
  rules:
    - host: vault.hospitalsm.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: infisical-infisical-standalone-infisical
                port:
                  number: 8080
